version: '3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    volumes:
      - type: bind
        source: /opt/csvserver/solution/inputFile
        target: /csvserver/inputdata
    ports:
      - "9393:9300"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - csvserver

