version: '3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    volumes:
      - type: bind
        source: /opt/csvserver/solution/inputFile
        target: /csvserver/inputdata
    ports:
      - "9393:9300"
